<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $keluarga = []

        $data = [
            [
                'user_id' => 1,
                'nik' => 'admin',
                'nama' => 'admin',
                'password' => bcrypt('admin'),
                'pekerjaan' => 'TNI',
                'notelp' => '82233617718',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => null,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'role' => '1',
                'keluarga' => null

            ],
            [
                'user_id' => 2,
                'nik' => '3507125403040001',
                'nama' => 'Yusriyah Firjatullah',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Presiden',
                'notelp' => '82233617719',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'malang',
                'tanggal_lahir' => '2003-09-27',
                // 'rt_id' => '1',
                'role' => '2', //ketua rw
                'keluarga' => '1'
            ],
            [
                'user_id' => 3,
                'nik' => '3507125403040002',
                'nama' => 'Putri Ayu',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Juragan Tebu',
                'notelp' => '82233617720',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Dampit',
                'tanggal_lahir' => '2004-07-20',
                // 'rt_id' => '2',
                'role' => '3', //ketua rt 2
                'keluarga' => '2'
            ],
            [
                'user_id' => 4,
                'nik' => '3507125403040003',
                'nama' => 'Maulita',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'wiraswasta',
                'notelp' => '82233617721',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'malang',
                'tanggal_lahir' => '1997-07-15',
                // 'rt_id' => '2',
                'role' => '4',
                'keluarga' => '3'
            ],
            [
                'user_id' => 5,
                'nik' => '3507125403040004',
                'nama' => 'Abdul',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'polisi',
                'notelp' => '82233617722',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'malang',
                'tanggal_lahir' => '1999-09-10',
                // 'rt_id' => '2',
                'role' => '5', //sekretaris rt 2
                'keluarga' => '3'
            ],
            [
                'user_id' => 6,
                'nik' => '3507125403040005',
                'nama' => 'Aziz',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '82233617723',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'surabaya',
                'tanggal_lahir' => '1983-01-01',
                // 'rt_id' => '2',
                'role' => '6', //bendahara 2
                'keluarga' => '3'
            ],
            [
                'user_id' => 7,
                'nik' => '3507125403040006',
                'nama' => 'Stevani',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'pelajar',
                'notelp' => '82233617724',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'surabaya',
                'tanggal_lahir' => '2009-09-10',
                // 'rt_id' => '1',
                'role' => '3', //ketua rt 1
                'keluarga' => '4'
            ],
            [
                'user_id' => 8,
                'nik' => '3507125403040007',
                'nama' => 'Cinta Laura',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'PNS',
                'notelp' => '82233617725',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'bengkulu',
                'tanggal_lahir' => '2000-10-11',
                // 'rt_id' => '1',
                'role' => '6', //bendahara rt 1
                'keluarga' => '4'
            ],
            [
                'user_id' => 9,
                'nik' => '3507125403040008',
                'nama' => 'Ariel Tatum',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '82233617726',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Mataram',
                'tanggal_lahir' => '1997-09-30',
                // 'rt_id' => '1',
                'role' => '5', //sekretaris rt 1
                'keluarga' => '4'
            ],
            [
                'user_id' => 10,
                'nik' => '3507125403040009',
                'nama' => 'Kelvin Julia Anggara',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Penyanyi',
                'notelp' => '82233617727',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Dampit',
                'tanggal_lahir' => '2004-01-02',
                // 'rt_id' => '3',
                'role' => '3',
                'keluarga' => '2'
            ],
            [
                'user_id' => 11,
                'nik' => '3507125403040010',
                'nama' => 'Bella Bonita',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'ibu rumah tanggga',
                'notelp' => '82233617728',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'madiun',
                'tanggal_lahir' => '1988-02-29',
                // 'rt_id' => '3',
                'role' => '5',
                'keluarga' => '5'
            ],
            [
                'user_id' => 12,
                'nik' => '3507125403040011',
                'nama' => 'Marselino',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Atlet',
                'notelp' => '82233617729',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'malang',
                'tanggal_lahir' => '2010-10-28',
                // 'rt_id' => '3',
                'role' => '6',
                'keluarga' => '5'
            ],
            [
                'user_id' => 13,
                'nik' => '3507125403040012',
                'nama' => 'Hasan',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'wiraswasta',
                'notelp' => '82233617730',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'malang',
                'tanggal_lahir' => '1985-11-18',
                // 'rt_id' => '4',
                'role' => '3',
                'keluarga' => '6'
            ],
            [
                'user_id' => 14,
                'nik' => '3507125403040013',
                'nama' => 'Nurul',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '82233617732',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'malang',
                'tanggal_lahir' => '1987-05-18',
                // 'rt_id' => '4',
                'role' => '5',
                'keluarga' => '6'
            ],
            [
                'user_id' => 15,
                'nik' => '3507125403040014',
                'nama' => 'Rose',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Mahasiswa',
                'notelp' => '82233617733',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'malang',
                'tanggal_lahir' => '2004-07-27',
                // 'rt_id' => '4',
                'role' => '6',
                'keluarga' => '6'
            ],
            [
                'user_id' => 16,
                'nik' => '3507125403040015',
                'nama' => 'Febri',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'wiraswasta',
                'notelp' => '82233617734',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'malang',
                'tanggal_lahir' => '1997-07-17',
                // 'rt_id' => '5',
                'role' => '3',
                'keluarga' => '7'
            ],
            [
                'user_id' => 17,
                'nik' => '3507125403040016',
                'nama' => 'Tatang',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'PNS',
                'notelp' => '82233617735',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'malang',
                'tanggal_lahir' => '2000-04-17',
                // 'rt_id' => '5',
                'role' => '5',
                'keluarga' => '7'
            ],
            [
                'user_id' => 18,
                'nik' => '3507125403040017',
                'nama' => 'Imam',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'PNS',
                'notelp' => '82233617736',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1974-03-30',
                // 'rt_id' => '5',
                'role' => '6',
                'keluarga' => '8'
            ],
            [
                'user_id' => 19,
                'nik' => '3507125403040018',
                'nama' => 'Asti Nurin',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Arsitek',
                'notelp' => '82233617737',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2003-11-14',
                // 'rt_id' => '5',
                'role' => '4',
                'keluarga' => '8'
            ],
            [
                'user_id' => 20,
                'nik' => '3507125403040019',
                'nama' => 'Choi Soobin',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Idol',
                'notelp' => '82233617738',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2000-12-05',
                // 'rt_id' => '5',
                'role' => '4',
                'keluarga' => '8'
            ],
            [
                'user_id' => 21,
                'nik' => '3507125403040020',
                'nama' => 'Daniel',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Idol',
                'notelp' => '82233617739',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1999-09-13',
                // 'rt_id' => '1',
                'role' => '4',
                'keluarga' => '9'
            ],
            [
                'user_id' => 22,
                'nik' => '3507125403040021',
                'nama' => 'Steve',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'wiraswasta',
                'notelp' => '82233617740',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2000-12-05',
                // 'rt_id' => '1',
                'role' => '6',
                'keluarga' => '9'
            ],
            [
                'user_id' => 23,
                'nik' => '3507125403040022',
                'nama' => 'Bagas',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'wiraswasta',
                'notelp' => '82233617741',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2001-03-13',
                // 'rt_id' => '3',
                'role' => '4',
                'keluarga' => '10'
            ],
            [
                'user_id' => 24,
                'nik' => '3507125403040023',
                'nama' => 'Terry',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Atlet',
                'notelp' => '82233617742',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2002-02-05',
                // 'rt_id' => '3',
                'role' => '5',
                'keluarga' => '10'
            ],
            [
                'user_id' => 25,
                'nik' => '3507125403040024',
                'nama' => 'Kamal Kai',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'mahasiswa',
                'notelp' => '82233617743',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2002-08-14',
                // 'rt_id' => '4',
                'role' => '4',
                'keluarga' => '11'
            ],
            [
                'user_id' => 26,
                'nik' => '3507125403040025',
                'nama' => 'Rahmat',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'pelajar',
                'notelp' => '82233617744',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2008-01-01',
                'role' => '4',
                'keluarga' => '12'
            ],
            [
                'user_id' => 27,
                'nik' => '3507125403040026',
                'nama' => 'Mawar',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'pelajar',
                'notelp' => '82233617745',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2008-02-02',
                'role' => '4',
                'keluarga' => '12'
            ],
            [
                'user_id' => 28,
                'nik' => '3507125403040027',
                'nama' => 'Budi',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'karyawan swasta',
                'notelp' => '82233617746',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1990-03-03',
                'role' => '4',
                'keluarga' => '12'
            ],
            [
                'user_id' => 29,
                'nik' => '3507125403040028',
                'nama' => 'Citra',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'dokter',
                'notelp' => '82233617747',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1995-04-04',
                'role' => '4',
                'keluarga' => '12'
            ],
            [
                'user_id' => 30,
                'nik' => '3507125403040029',
                'nama' => 'Dewi',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '82233617748',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1975-05-05',
                'role' => '4',
                'keluarga' => '13'
            ],
            [
                'user_id' => 31,
                'nik' => '3507125403040030',
                'nama' => 'Ilham',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Dosen',
                'notelp' => '82233617749',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1985-06-06',
                'role' => '4',
                'keluarga' => '13'
            ],
            [
                'user_id' => 32,
                'nik' => '3507125403040031',
                'nama' => 'Naufal',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'Arsitek',
                'notelp' => '82233617750',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1990-07-07',
                'role' => '4',
                'keluarga' => '13'
            ],
            [
                'user_id' => 33,
                'nik' => '3507125403040032',
                'nama' => 'Gina',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '82233617751',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1995-08-08',
                'role' => '4',
                'keluarga' => '13'
            ],
            [
                'user_id' => 34,
                'nik' => '3507125403040033',
                'nama' => 'Hasan',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'wirausaha',
                'notelp' => '82233617752',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1980-09-09',
                'role' => '4',
                'keluarga' => '14'
            ],
            [
                'user_id' => 35,
                'nik' => '3507125403040034',
                'nama' => 'Ika',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'dokter',
                'notelp' => '82233617753',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1985-10-10',
                'role' => '4',
                'keluarga' => '14'
            ],
            [
                'user_id' => 36,
                'nik' => '3507125403040035',
                'nama' => 'Joko',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'guru',
                'notelp' => '82233617754',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1990-11-11',
                'role' => '4',
                'keluarga' => '14'
            ],
            [
                'user_id' => 37,
                'nik' => '3507125403040036',
                'nama' => 'Kiki',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '82233617755',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1995-12-12',
                'role' => '4',
                'keluarga' => '14'
            ],
            [
                'user_id' => 38,
                'nik' => '3507125403040037',
                'nama' => 'Lina',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'guru',
                'notelp' => '82233617756',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1980-01-01',
                'role' => '4',
                'keluarga' => '15'
            ],
            [
                'user_id' => 39,
                'nik' => '3507125403040038',
                'nama' => 'Miko',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'wirausaha',
                'notelp' => '82233617757',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1985-02-02',
                'role' => '4',
                'keluarga' => '15'
            ],
            [
                'user_id' => 40,
                'nik' => '3507125403040039',
                'nama' => 'Nina',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '82233617758',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1990-03-03',
                'role' => '4',
                'keluarga' => '15'
            ],
            [
                'user_id' => 41,
                'nik' => '3507125403040040',
                'nama' => 'Albi',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'dokter',
                'notelp' => '82233617759',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1995-04-04',
                'role' => '4',
                'keluarga' => '15'
            ],
            [
                'user_id' => 42,
                'nik' => '3507125403040041',
                'nama' => 'Putri',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'guru',
                'notelp' => '82233617760',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1980-05-05',
                'role' => '4',
                'keluarga' => '16'
            ],
            [
                'user_id' => 43,
                'nik' => '3507125403040042',
                'nama' => 'Rizal',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'wirausaha',
                'notelp' => '82233617761',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1985-06-06',
                'role' => '4',
                'keluarga' => '16'
            ],
            [
                'user_id' => 44,
                'nik' => '3507125403040043',
                'nama' => 'Sari',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'dokter',
                'notelp' => '82233617762',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1990-07-07',
                'role' => '4',
                'keluarga' => '16'
            ],
            [
                'user_id' => 45,
                'nik' => '3507125403040044',
                'nama' => 'Teguh',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '82233617763',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1995-08-08',
                'role' => '4',
                'keluarga' => '16'
            ],
            [
                'user_id' => 46,
                'nik' => '3507125403040045',
                'nama' => 'Andi',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'guru',
                'notelp' => '81234567890',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1980-05-20',
                'role' => '4',
                'keluarga' => '17'
            ],
            [
                'user_id' => 47,
                'nik' => '3507125403040046',
                'nama' => 'Budi Santoso',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'petani',
                'notelp' => '81234567891',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1985-06-15',
                'role' => '4',
                'keluarga' => '17'
            ],
            [
                'user_id' => 48,
                'nik' => '3507125403040047',
                'nama' => 'Chika',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'pelajar',
                'notelp' => '81234567892',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2007-11-10',
                'role' => '4',
                'keluarga' => '17'
            ],
            [
                'user_id' => 49,
                'nik' => '3507125403040048',
                'nama' => 'Dewi Sinta',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'dokter',
                'notelp' => '81234567893',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2003-09-19',
                'role' => '4',
                'keluarga' => '17'
            ],
            [
                'user_id' => 50,
                'nik' => '3507125403040049',
                'nama' => 'Eka',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'polisi',
                'notelp' => '81234567894',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1983-03-14',
                'role' => '4',
                'keluarga' => '18'
            ],
            [
                'user_id' => 51,
                'nik' => '3507125403040050',
                'nama' => 'Fani',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'guru',
                'notelp' => '81234567895',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1987-09-19',
                'role' => '4',
                'keluarga' => '18'
            ],
            [
                'user_id' => 52,
                'nik' => '3507125403040050',
                'nama' => 'Gilang',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '81234567896',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1995-05-05',
                'role' => '4',
                'keluarga' => '18'
            ],
            [
                'user_id' => 53,
                'nik' => '3507125403040051',
                'nama' => 'Hana',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '81234567897',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1992-02-22',
                'role' => '4',
                'keluarga' => '18'
            ],
            [
                'user_id' => 54,
                'nik' => '3507125403040052',
                'nama' => 'Harrel',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'dokter',
                'notelp' => '81234567898',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1981-01-11',
                'role' => '4',
                'keluarga' => '19'
            ],
            [
                'user_id' => 55,
                'nik' => '3507125403040054',
                'nama' => 'Joko',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'polisi',
                'notelp' => '81234567899',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1984-07-07',
                'role' => '4',
                'keluarga' => '19'
            ],
            [
                'user_id' => 56,
                'nik' => '3507125403040055',
                'nama' => 'Amelia',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'guru',
                'notelp' => '81234567900',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1994-10-10',
                'role' => '4',
                'keluarga' => '19'
            ],
            [
                'user_id' => 57,
                'nik' => '3507125403040056',
                'nama' => 'Lina',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '81234567901',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1991-06-06',
                'role' => '4',
                'keluarga' => '19'
            ],
        
            [
                'user_id' => 58,
                'nik' => '3507125403040057',
                'nama' => 'Mira',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '81234567902',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1988-03-03',
                'role' => '4',
                'keluarga' => '20'
            ],
            [
                'user_id' => 59,
                'nik' => '3507125403040058',
                'nama' => 'Nina',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'dokter',
                'notelp' => '81234567903',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1982-08-08',
                'role' => '4',
                'keluarga' => '20'
            ],
            [
                'user_id' => 60,
                'nik' => '3507125403040059',
                'nama' => 'Omar',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'polisi',
                'notelp' => '81234567904',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1993-12-12',
                'role' => '4',
                'keluarga' => '20'
            ],
            [
                'user_id' => 61,
                'nik' => '3507125403040060',
                'nama' => 'Chia',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'guru',
                'notelp' => '81234567905',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1996-09-09',
                'role' => '4',
                'keluarga' => '20'
            ],
            
            [
                'user_id' => 62,
                'nik' => '3507125403040061',
                'nama' => 'Qori',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'petani',
                'notelp' => '81234567906',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1980-02-02',
                'role' => '4',
                'keluarga' => '21'
            ],
            [
                'user_id' => 63,
                'nik' => '3507125403040062',
                'nama' => 'Rina',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'dokter',
                'notelp' => '81234567907',
                'status_perkawinan' => 'kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1986-07-21',
                'role' => '4',
                'keluarga' => '21'
            ],
            [
                'user_id' => 64,
                'nik' => '3507125403040063',
                'nama' => 'Rika',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'swasta',
                'notelp' => '81234567908',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1997-05-05',
                'role' => '4',
                'keluarga' => '21'
            ],
            [
                'user_id' => 65,
                'nik' => '3507125403040064',
                'nama' => 'Tomi',
                'password' => bcrypt('12345'),
                'pekerjaan' => 'guru',
                'notelp' => '81234567909',
                'status_perkawinan' => 'belum kawin',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1991-11-11',
                'role' => '4',
                'keluarga' => '21'
            ],
        ];
        DB::table('users')->insert($data);
    }
}