<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $keluarga = []

        $data = [
            [
                // 'user_id' => 1,
                'nik' => '2241720178',
                'nama' => 'Yusriyah Firjatullah',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'TNI',
                'notelp'=>'82233617718',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'2004-06-20',
                // 'rt_id' => '1',
                'role' => '1',
                'keluarga' => '1'

            ],
            [
                // 'user_id' => 2,
                'nik' => '2241720171',
                'nama' => 'Asti Nurin',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'ibu rumah tangga',
                'notelp'=>'82233617719',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'2003-06-21',
                // 'rt_id' => '1',
                'role' => '2',
                'keluarga' => '1'
            ],
            [
                // 'user_id' => 3,
                'nik' => '2241720172',
                'nama' => 'Putri Ayu',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'Polwan',
                'notelp'=>'82233617720',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'2004-07-20',
                // 'rt_id' => '2',
                'role' => '3',
                'keluarga' => '2'
            ],
            [
                // 'user_id' => 4,
                'nik' => '2241720173',
                'nama' => 'Maulita',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'wiraswasta',
                'notelp'=>'82233617721',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'1997-07-15',
                // 'rt_id' => '2',
                'role' => '4',
                'keluarga' => '3'
            ],
            [
                // 'user_id' => 5,
                'nik' => '2241720174',
                'nama' => 'Abdul',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'polisi',
                'notelp'=>'82233617722',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'1999-09-10',
                // 'rt_id' => '2',
                'role' => '5',
                'keluarga' => '3'
            ],
            [
                // 'user_id' => 6,
                'nik' => '2241720175',
                'nama' => 'Aziz',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'swasta',
                'notelp'=>'82233617723',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'surabaya',
                'tanggal_lahir'=>'1983-01-01',
                // 'rt_id' => '2',
                'role' => '6',
                'keluarga' => '3'
            ],
            [
                // 'user_id' => 7,
                'nik' => '2241720176',
                'nama' => 'Stevani',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'pelajar',
                'notelp'=>'82233617724',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'surabaya',
                'tanggal_lahir'=>'2009-09-10',
                // 'rt_id' => '1',
                'role' => '3',
                'keluarga' => '4'
            ],
            [
                // 'user_id' => 8,
                'nik' => '2241720177',
                'nama' => 'Cinta Laura',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'PNS',
                'notelp'=>'82233617725',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'bengkulu',
                'tanggal_lahir'=>'2000-10-11',
                // 'rt_id' => '1',
                'role' => '6',
                'keluarga' => '4'
            ],
            [
                // 'user_id' => 9,
                'nik' => '2241720178',
                'nama' => 'Ariel Tatum',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'Mahasiswa',
                'notelp'=>'82233617726',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'Mataram',
                'tanggal_lahir'=>'1997-09-30',
                // 'rt_id' => '1',
                'role' => '5',
                'keluarga' => '4'
            ],
            [
                // 'user_id' => 10,
                'nik' => '2241720179',
                'nama' => 'Denny Caknan',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'Penyanyi',
                'notelp'=>'82233617727',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'ngawi',
                'tanggal_lahir'=>'1985-02-14',
                // 'rt_id' => '3',
                'role' => '3',
                'keluarga' => '5'
            ],
            [
                // 'user_id' => 11,
                'nik' => '2241720180',
                'nama' => 'Bella Bonita',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'ibu rumah tanggga',
                'notelp'=>'82233617728',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'madiun',
                'tanggal_lahir'=>'1988-02-29',
                // 'rt_id' => '3',
                'role' => '5',
                'keluarga' => '5'
            ],
            [
                // 'user_id' => 12,
                'nik' => '2241720181',
                'nama' => 'Marselino',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'Atlet',
                'notelp'=>'82233617729',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'2010-10-28',
                // 'rt_id' => '3',
                'role' => '6',
                'keluarga' => '5'
            ],
            [
                // 'user_id' => 13,
                'nik' => '2241720182',
                'nama' => 'Hasan',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'wiraswasta',
                'notelp'=>'82233617730',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'1985-11-18',
                // 'rt_id' => '4',
                'role' => '3',
                'keluarga' => '6'
            ],
            [
                // 'user_id' => 14,
                'nik' => '2241720183',
                'nama' => 'Nurul',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'swasta',
                'notelp'=>'82233617732',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'1987-05-18',
                // 'rt_id' => '4',
                'role' => '5',
                'keluarga' => '6'
            ],
            [
                // 'user_id' => 15,
                'nik' => '2241720184',
                'nama' => 'Rosalinda',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'Mahasiswa',
                'notelp'=>'82233617733',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'2004-07-27',
                // 'rt_id' => '4',
                'role' => '6',
                'keluarga' => '6'
            ],
            [
                // 'user_id' => 16,
                'nik' => '2241720185',
                'nama' => 'Febri',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'wiraswasta',
                'notelp'=>'82233617734',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'1997-07-17',
                // 'rt_id' => '5',
                'role' => '3',
                'keluarga' => '7'
            ],
            [
                // 'user_id' => 17,
                'nik' => '2241720186',
                'nama' => 'Arlida',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'PNS',
                'notelp'=>'82233617735',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'malang',
                'tanggal_lahir'=>'2000-04-17',
                // 'rt_id' => '5',
                'role' => '5',
                'keluarga' => '7'
            ],
            [
                // 'user_id' => 18,
                'nik' => '2241720187',
                'nama' => 'Imam',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'PNS',
                'notelp'=>'82233617736',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'Bandung',
                'tanggal_lahir'=>'1974-03-30',
                // 'rt_id' => '5',
                'role' => '6',
                'keluarga' => '8'
            ],
            [
                // 'user_id' => 19,
                'nik' => '2241720188',
                'nama' => 'Murti',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'ibu rumah tangga',
                'notelp'=>'82233617737',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'Malang',
                'tanggal_lahir'=>'1976-08-30',
                // 'rt_id' => '5',
                'role' => '4',
                'keluarga' => '8'
            ],
            [
                // 'user_id' => 20,
                'nik' => '2241720189',
                'nama' => 'Sulis',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'Mahasiswa',
                'notelp'=>'82233617738',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'Malang',
                'tanggal_lahir'=>'2005-08-17',
                // 'rt_id' => '5',
                'role' => '4',
                'keluarga' => '8'
            ],
            [
                // 'user_id' => 21,
                'nik' => '2241720190',
                'nama' => 'Sois',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'wirausaha',
                'notelp'=>'82233617739',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'Malang',
                'tanggal_lahir'=>'1977-07-17',
                // 'rt_id' => '1',
                'role' => '4',
                'keluarga' => '9'
            ],
            [
                // 'user_id' => 22,
                'nik' => '2241720190',
                'nama' => 'Solika',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'ibu rumah tangga',
                'notelp'=>'82233617740',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'Malang',
                'tanggal_lahir'=>'1979-09-19',
                // 'rt_id' => '1',
                'role' => '6',
                'keluarga' => '9'
            ],
            [
                // 'user_id' => 23,
                'nik' => '2241720191',
                'nama' => 'Badrul',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'TNI',
                'notelp'=>'82233617741',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'Malang',
                'tanggal_lahir'=>'1968-08-18',
                // 'rt_id' => '3',
                'role' => '4',
                'keluarga' => '10'
            ],
            [
                // 'user_id' => 24,
                'nik' => '2241720192',
                'nama' => 'Siti',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'swasta',
                'notelp'=>'82233617742',
                'status_perkawinan'=>'kawin',
                'jenis_kelamin'=>'perempuan',
                'tempat_lahir'=>'Situbondo',
                'tanggal_lahir'=>'1970-10-09',
                // 'rt_id' => '3',
                'role' => '5',
                'keluarga' => '10'
            ],
            [
                // 'user_id' => 25,
                'nik' => '2241720193',
                'nama' => 'Sutejo',
                'password' => bcrypt('12345'),
                'pekerjaan'=>'wirausaha',
                'notelp'=>'82233617743',
                'status_perkawinan'=>'belum kawin',
                'jenis_kelamin'=>'laki-laki',
                'tempat_lahir'=>'Malang',
                'tanggal_lahir'=>'1955-05-05',
                // 'rt_id' => '4',
                'role' => '4',
                'keluarga' => '11'
            ],
        ];
        DB::table('users')->insert($data);
    }
}
